function saveHighScore(newScore) {
    // Get the existing high scores from LocalStorage
    let highScores = JSON.parse(localStorage.getItem('highScores')) || [];

    // Add the new score to the array
    highScores.push(newScore);

    // Sort the scores in descending order (higher scores first)
    highScores.sort((a, b) => b.score - a.score);

    // Optionally, limit the number of high scores saved (e.g., top 10)
    highScores = highScores.slice(0, 10);

    // Save the updated high scores back to LocalStorage
    localStorage.setItem('highScores', JSON.stringify(highScores));
}

function getHighScores() {
    // Retrieve the high scores from LocalStorage
    let highScores = JSON.parse(localStorage.getItem('highScores')) || [];
    return highScores;
}

function displayHighScores() {
    const highScores = getHighScores();
    const highScoresTableBody = document.querySelector('#highScoresTable tbody');

    // Clear any existing scores in the table
    highScoresTableBody.innerHTML = '';

    // Display the high scores
    highScores.forEach((score, index) => {
        const row = document.createElement('tr');

        const rankCell = document.createElement('td');
        rankCell.textContent = `#${index + 1}`;
        row.appendChild(rankCell);

        const playerCell = document.createElement('td');
        playerCell.textContent = score.player; // Assuming score object has a player property
        row.appendChild(playerCell);

        const scoreCell = document.createElement('td');
        scoreCell.textContent = score.score; // Assuming score object has a score property
        row.appendChild(scoreCell);

        highScoresTableBody.appendChild(row);
    });
}

// Remove once real high scores are generated by gameplay
function generateFictitiousHighScores() {
    const fictitiousScores = [
        { player: 'Luke Skywalker', score: 1200 },
        { player: 'Darth Vader', score: 1100 },
        { player: 'Leia Organa', score: 1000 },
        { player: 'Han Solo', score: 900 },
        { player: 'Yoda', score: 800 },
        { player: 'Obi-Wan Kenobi', score: 700 },
        { player: 'Chewbacca', score: 600 },
        { player: 'R2-D2', score: 500 },
        { player: 'C-3PO', score: 400 },
        { player: 'Boba Fett', score: 300 }
    ];

    // Save the fictitious high scores to LocalStorage
    localStorage.setItem('highScores', JSON.stringify(fictitiousScores));
}